# Sections content configuration file
##
### use navigation.yml file to re-order, delete or add section of each card
### here you can find all content in all pre-build sections

### About [ about ]
about:
  image: "assets/img/man2.jpg"
  text: "<p>Hi! Welcome to my personal page, I’m Alexis Villegas. Full Stack Developer. I have rich experience in web app design and building, from all of the sides; Front-End Back-End, also I am good at wordpress. I love to talk with you about my unique skills.</p>"
  list:
    - label: "Age"
      value: "22"

    - label: "Residence"
      value: "Ecuador"

    - label: "Freelance"
      value: "Available"

    - label: "Address"
      value: "Riobamba"

    - label: "Phone"
      value: "+593 (99) 6535731"

    - label: "E-mail"
      value: "programmlab@outlook.es"

  download:
    text: "Download CV"
    link: "https://drive.google.com/"

### Services [ services ]
services:
  title: "Services"
  items:
    - icon: "fas fa-code"
      name: "Web Development"
      text: "Modern and mobile-ready website with Laravel and React."

    - icon: "fas fa-atom"
      name: "SOLID Fundamentals and Clean Code"
      text: "Code Refactoring, make code readable and usable for the advancement of the project."

    - icon: "fas fa-ad"
      name: "MERN Fundamentals"
      text: "In the order of the continuos learning, MERN is the next step in my trajectory"

    - icon: "fas fa-mobile-alt"
      name: "Mobile Development"
      text: "Games, playing music, handle network transactions, interacting content etc."

    - icon: "fas fa-paper"
      name: "SCRUM Fundamentals"
      text: "Experiencie from SCRUM Master, for the manage and deploy of projects."

    - icon: "fas fa-camera"
      name: "3+ years Experience"
      text: "Our in-house photography services team made up of professional photographers."

### Pricing [ pricing ]
#pricing:
# title: "Pricing"
#items:
# - icon: "fas fa-star"
## price: "39"
#  price_before: "$"
# price_after: "hour"
#list:
# - value: "Web Development"
#  disable: "no"
#        - value: "Advetising"
#         disable: "no"
#      - value: "Game Development"
#       disable: "no"
#    - value: "Music Writing"
#     disable: "yes"
#  - value: "Photography"
#   disable: "yes"
#    button: "Buy Now"
#   link: "contact/"

#    - icon: "fas fa-rocket"
#     name: "Premium"
#    price: "59"
#   price_before: "$"
#  price_after: "hour"
# list:
#  - value: "Web Development"
#   disable: "no"
#  - value: "Advetising"
#     disable: "no"
#    - value: "Game Development"
#  disable: "no"
# - value: "Music Writing"
#    disable: "no"
#   - value: "Photography"
#      disable: "no"
#   button: "Buy Now"
#    link: "contact/"

### Resume [ resume ]
resume:
  experience:
    title: "Experience"
    items:
      - year: "2021 - Present"
        name: "Full Stack Developer - UNACH"
        text: "Final Work for obtaining the title of IT engineer, Salva PET system for the vet healthcare with Laravel 7."

      - year: "2021 - 2022"
        name: "Wordpress Developer - UNACH"
        text: "Development of the website for the ICTALK 2022."

      - year: "2021 February - 2021 August"
        name: "Wordpress Developer - YUWARMI"
        text: "Development of an invoice system and sale of endemic bags."

      - year: "2020 October - 2021 February"
        name: "Full Stack Developer - Perfect Dental"
        text: "Development of an informational website for the company Perfect Dental with native technologies: HTML, CSS, JS, Jquery."

  education:
    title: "Education"
    items:
      - year: "2017 - 2022"
        name: "National University of Chimborazo"
        text: "IT engineer in Unach, Riobamba, Chimborazo"

      - year: "2005 - 2006"
        name: "Programming Course"
        text: "Coursework - Git, WordPress, Javascript, iOS, Android."

      - year: "2004 - 2005"
        name: "Web Design Course"
        text: "Converted Photoshop layouts to web pages using HTML, CSS, and JavaScript"

### Skills [ skills ]
skills:
  columns:
    - type: "default" #skills progress type - default, dotted, circles, list
      title: "Design Skills"
      items:
        - label: "Web Design"
          value: "70" #0-100 progress in %

        - label: "Illustrations"
          value: "90" #0-100 progress in %

        - label: "Photoshop"
          value: "75" #0-100 progress in %

        - label: "Graphic Design"
          value: "80" #0-100 progress in %

    - type: "dotted" #skills progress type - default, dotted, circles, list
      title: "Languages Skills"
      items:
        - label: "English"
          value: "90" #0-100 progress in %

        - label: "German"
          value: "70" #0-100 progress in %

        - label: "Italian"
          value: "55" #0-100 progress in %

        - label: "French"
          value: "85" #0-100 progress in %

    - type: "circles" #skills progress type - default, dotted, circles, list
      title: "Coding Skills"
      items:
        - label: "WordPress"
          value: "95" #0-100 progress in %

        - label: "PHP / MYSQL"
          value: "75" #0-100 progress in %

        - label: "Angular / JavaScript"
          value: "85" #0-100 progress in %

        - label: "HTML / CSS"
          value: "90" #0-100 progress in %

    - type: "list" #skills progress type - default, dotted, circles, list
      title: "Knowledge"
      items:
        - label: "Website hosting"
          value: "" #0-100 progress in %

        - label: "iOS and android apps"
          value: "" #0-100 progress in %

        - label: "Create logo design"
          value: "" #0-100 progress in %

        - label: "Design for print"
          value: "" #0-100 progress in %

        - label: "Modern and mobile-ready"
          value: "" #0-100 progress in %

        - label: "Advertising services include"
          value: "" #0-100 progress in %

        - label: "Graphics and animations"
          value: "" #0-100 progress in %

        - label: "Search engine marketing"
          value: "" #0-100 progress in %

### Facts [ facts ]
facts:
  title: "Interests"
  items:
    - icon: "fas fa-baseball-ball"
      name: "Basketball"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-campground"
      name: "Camping"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-chess-knight"
      name: "Chess"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - icon: "fas fa-headphones"
      name: "Music"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

### Team [ team ]
team:
  title: "Our Team"
  items:
    - image: "assets/img/team/team1.jpg"
      name: "Alejandro Abeyta"
      role: "Web Developer"
      social:
        - url: "https://www.pinterest.com/"
          icon: "fab fa-pinterest"
        - url: "https://www.instagram.com/"
          icon: "fab fa-instagram"
        - url: "https://dribbble.com/"
          icon: "fab fa-dribbble"

    - image: "assets/img/team/team2.jpg"
      name: "Peter Green"
      role: "Back-end Developer"
      social:
        - url: "https://www.pinterest.com/"
          icon: "fab fa-pinterest"
        - url: "https://www.instagram.com/"
          icon: "fab fa-instagram"
        - url: "https://dribbble.com/"
          icon: "fab fa-dribbble"

### Testimonials [ testimonials ]
testimonials:
  title: "Testimonials"
  items:
    - image: "assets/img/testimonials/rev1.jpg"
      name: "Helen Floyd"
      role: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - image: "assets/img/testimonials/rev1.jpg"
      name: "Helen Floyd"
      role: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

### Clients [ clients ]
clients:
  title: "Clients"
  items:
    - url: "https://www.google.com"
      image: "assets/img/clients/client1.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client2.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client3.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client4.png"

### Custom Text [ text ]
text:
  title: "Custom Text"
  text: "
    <p>
    Now there is more fashion. There is no so-called trends. Now chase after anything not necessary — nor for fashionable color nor the shape, nor for style. Think about the content that you want to invest in a created object, and only then will form. The thing is your spirit. A spirit unlike forms hard copy.
    </p>
    <p>
    Here choose yourself like that, without any looking back, do your personal, home, small fashion, and all will be well.
    </p>
    "

### Contact Info [ contacts-info ]
contacts_info:
  title: "Contacts Info"
  list:
    - label: "Phone"
      icon: "fas fa-phone"
      value: "+ (231) 456 67 89"

    - label: "Email"
      icon: "fas fa-envelope"
      value: "<a href='mailto:steve-pearson@gmail.com'>steve-pearson@gmail.com</a>"

    - label: "Address"
      icon: "fas fa-map-marker-alt"
      value: "2621 W Pico Blvd, Los Angeles"

    - label: "Freelance Available"
      icon: "fas fa-user-tie"
      value: "I am available for Freelance hire"

### Contact Form [ contacts-form ]
contacts_form:
  title: "Contact Form"
